### ISSUE TITLE
Dumps core: Assertion `systemalltime >= cpuData->systemAllTime' failed

### ISSUE THREAD

**Issue by nfnty** [hishamhm/htop#159]
Result of bisect is that this commit is causing the issue: eb229d9aefa622d3ae25fc7c92b9f66590216d8b

Output before core dumped:

    htop: linux/LinuxProcessList.c:660: LinuxProcessList_scanCPUTime: Assertion `systemalltime >= cpuData->systemAllTime' failed

gdb backtrace:

    #0  0x00000299e0ac3a97 in raise () from /usr/lib/libc.so.6
    #1  0x00000299e0ac4e6a in abort () from /usr/lib/libc.so.6
    #2  0x00000299e0abc8bd in __assert_fail_base () from /usr/lib/libc.so.6
    #3  0x00000299e0abc972 in __assert_fail () from /usr/lib/libc.so.6
    #4  0x000000000041e08a in LinuxProcessList_scanCPUTime (this=0xc90c60) at linux/LinuxProcessList.c:660
    #5  0x000000000041e3ef in ProcessList_scan (this=0xc90c60) at linux/LinuxProcessList.c:700
    #6  0x000000000040d66c in main (argc=1, argv=0x3a021e5cee8) at htop.c:712

**Comment by hishamhm** [comment]
Thank you for the detailed report! It should be fixed now!

**Comment by nfnty** [comment]
Still crashing. Output now:

    htop: linux/LinuxProcessList.c:169: LinuxProcessList_readStatFile: Assertion `location == ((void *)0)' failed.

Backtrace:

    #0  0x000002e7863ada97 in raise () from /usr/lib/libc.so.6
    #1  0x000002e7863aee6a in abort () from /usr/lib/libc.so.6
    #2  0x000002e7863a68bd in __assert_fail_base () from /usr/lib/libc.so.6
    #3  0x000002e7863a6972 in __assert_fail () from /usr/lib/libc.so.6
    #4  0x000000000041c1ae in ?? ()
    #5  0x000000000041d49c in ?? ()
    #6  0x000000000041e492 in ProcessList_scan ()
    #7  0x000000000040d66c in main ()

**Comment by hishamhm** [comment]
Your kernel is probably returning more data then htop expects. Please open a shell and run this:
```
cat /proc/$$/stat | wc -w
```
What's the output? On my machine I get `52`.

**Comment by nfnty** [comment]
`52` here as well.

**Comment by nfnty** [comment]
Here's the full backtrace:

    #0  0x00007f3c37a00a97 in raise () from /usr/lib/libc.so.6
    #1  0x00007f3c37a01e6a in abort () from /usr/lib/libc.so.6
    #2  0x00007f3c379f98bd in __assert_fail_base () from /usr/lib/libc.so.6
    #3  0x00007f3c379f9972 in __assert_fail () from /usr/lib/libc.so.6
    #4  0x000000000041c1ae in LinuxProcessList_readStatFile (process=0xa77510, dirname=0x422882 "/proc", name=0xa6fc13 "1", command=0x7fff37498c50 "systemd") at linux/LinuxProcessList.c:169
    #5  0x000000000041d49c in LinuxProcessList_processEntries (this=0x9df010, dirname=0x422882 "/proc", parent=0x0, period=26671.25, tv=...) at linux/LinuxProcessList.c:490
    #6  0x000000000041e492 in ProcessList_scan (this=0x9df010) at linux/LinuxProcessList.c:715
    #7  0x000000000040d66c in main (argc=1, argv=0x7fff37499ff8) at htop.c:712

**Comment by hishamhm** [comment]
From what I can see here, that assert is bogus. Is just a matter of removing it.

**Comment by nfnty** [comment]
Still crashing.

    htop: malloc.c:2368: sysmalloc: Assertion `(old_top == (((mbinptr) (((char *) &((av)->bins[((1) - 1) * 2])) - __builtin_offsetof (struct malloc_chunk, fd)))) && old_size == 0) || ((unsigned long) (old_size) >= (unsigned long)((((__builtin_offsetof (struct malloc_chunk, fd_nextsize))+((2 *(sizeof(size_t))) - 1)) & ~((2 *sizeof(size_t))) - 1))) && ((old_top)->size & 0x1 && ((unsigned long) old_end & pagemask) == 0)' failed.

Backtrace:

    #0  0x000002a8a11bca97 in raise () from /usr/lib/libc.so.6
    #1  0x000002a8a11bde6a in abort () from /usr/lib/libc.so.6
    #2  0x000002a8a12011e8 in __malloc_assert () from /usr/lib/libc.so.6
    #3  0x000002a8a120396c in _int_malloc () from /usr/lib/libc.so.6
    #4  0x000002a8a120513e in malloc () from /usr/lib/libc.so.6
    #5  0x000002a8a11f321d in __fopen_internal () from /usr/lib/libc.so.6
    #6  0x000000000041cddc in LinuxProcessList_readVServerData (process=0x1ca0610, dirname=0x42282a "/proc", name=0x1c974ab "2") at linux/LinuxProcessList.c:339
    #7  0x000000000041d701 in LinuxProcessList_processEntries (this=0x1c068d0, dirname=0x42282a "/proc", parent=0x0, period=10242465.75, tv=...) at linux/LinuxProcessList.c:511
    #8  0x000000000041e46d in ProcessList_scan (this=0x1c068d0) at linux/LinuxProcessList.c:714
    #9  0x000000000040d66c in main (argc=1, argv=0x38f9fa79658) at htop.c:712

**Comment by nfnty** [comment]
Any updates?
