### ISSUE TITLE
Broken background colors under tmux

### ISSUE THREAD

**Issue by mmarzantowicz** [hishamhm/htop#739]
I'm using `htop` a lot under `tmux` (terminal multiplexer). Since upgrade from 2.0.2 to 2.1.0 I'm experiencing some defects in `htop` not present in 2.0.x .

To illustrate what am I talking about I attach two images - one with `htop` and `tmux` and one without `tmux`:

- ![htop-01](https://user-images.githubusercontent.com/904394/36278279-b35d6860-1293-11e8-9336-4532045fa815.png)

- ![htop-02](https://user-images.githubusercontent.com/904394/36278351-e294c3d0-1293-11e8-82ac-79b30f40a916.png)

What is the recommended way to debug this issue or maybe it's already known?

**Comment by hishamhm** [comment]
This is fixed in the latest `master`, 2.1.1 is coming :)

**Comment by karimn** [comment]
I'm using version 2.6 but I'm still seeing the black squares as above.

**Comment by usbhub** [comment]
> I'm using version 2.6 but I'm still seeing the black squares as above.

To clarify for anyone else reading, I believe karimn was looking at his tmux version, while this is fixed in htop itself. I am on ubuntu 18.04 and unfortunately the new version of htop (>=2.1.1) is not in the repos (only 2.1.0: https://launchpad.net/ubuntu/bionic/+source/htop ), so I had to install it from the provided tars like this:

```
sudo apt-get install libncursesw5-dev
wget https://hisham.hm/htop/releases/2.2.0/htop-2.2.0.tar.gz
tar xvf htop-2.2.0.tar.gz
cd htop-2.2.0/
./configure && make
sudo make install
```

This fixed the black bars issue in tmux for me. Hopefully it helps.
