### ISSUE TITLE
Virtualization color is incorrect when comparing the graphs and the help

### ISSUE THREAD

**Issue by FurretUber** [hishamhm/htop#785]
In htop help, the CPU load help is shown different colors depending of the type of task: low priority, normal, kernel, and virtualization. On xterm, the colors are blue, green, red and cyan. However, in the htop meters, it's shown blue, green, red and yellow.

Apparently, cyan and yellow are swapped, so the virtualization load has a incorrect color.

I have tested htop with xfce4-terminal and xterm:

xfce4-terminal help: https://i.imgur.com/R43NhOJ.png

xfce4-terminal meters: https://i.imgur.com/sOqByY8.png

xterm help: https://i.imgur.com/E5s5vr7.png

xterm meters: https://i.imgur.com/ptzZSio.png

I have reported this on Launchpad and it was asked to try to build from upstream, I have built from master and it's showing the same issue.

Launchpad bug: https://bugs.launchpad.net/ubuntu/+source/htop/+bug/1766030

OS.: Xubuntu 18.04 Bionic Beaver (development branch)

**Comment by hishamhm** [comment]
@FurretUber thank you for the report! It is now fixed in master.

**Comment by FurretUber** [comment]
I have cloned the updated repository, but it is still showing the colors the same way as before, yellow in the meter and cyan in the help. I tried with other theme colors and they show different colors too.
